package ui.battleUI.battleRequests;

public enum RequestWithoutVariableEnum {

    GAME_INFO_REQUEST,
    SHOW_MY_MINIONS_REQUEST,
    SHOW_OPPONENT_MINIONS_REQUEST,
    SHOW_NEXT_CARD_REQUEST,
    SHOW_HAND_REQUEST,
    END_TURN_REQUEST,
    SHOW_COLLECTED_ITEM_REQUEST,
    END_GAME_REQUEST,
    HELP_REQUEST
}
