package packet.clientPacket;


public enum ClientEnum {

    CHAT_ROOM,
    LEADER_BOARD,
    MATCH_HISTORY,
    SHOP,
    COLLECTION,
    GET_MONEY,
    SAVE,
    CANCEL_WAITING_FOR_MULTI_PLAYER_GAME,
    EXIT_CHATROOM,
    MULTI_PLAYER,
    SINGLE_PLAYER,
    CHECK_DECK,
    LEADER_BOARD_ONLINE,
    AUCTION
}
